### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by lucaspinto**
This PR improves some of the formulations, correct a couple of mistakes, extend the "Requirements" paragraph that some users had trouble understanding and add an embeded yotube video about the tile to the index.

### CODE REVIEW

**Comment by ghanna2017** [comment]
Thanks @lucaspinto. We'll do an edit pass on this and push it out.

**Comment by lucaspinto** [comment]
Thank you @ghanna2017 !

**Comment by jncd** [comment]
Hi @lucaspinto  (@ghanna2017)

The video isn't rendering consistently on some of our browsers.
Does it always work for you?  It's an issue with http vs https — If I'm using https I have to agree to load a script from an unauthorized source. 

Two solutions are:
1. Replace the inline video with a link to youtube.
2. Add a line below the video embed that says something like this: "If you do not see the video in your browser, view it on YouTube: [a9s RabbitMQ Data Service for Pivotal Cloud Foundry](http://www.youtube.com/...)."   

TIA, jane

**Comment by lucaspinto** [comment]
@jncd Have you had this issue with the other videos as well?

**Comment by jncd** [comment]
@lucaspinto So far, we've just integrated the RabbitMQ and MongoDB — same issue. 
Does anyone in your company have trouble seeing the video on the docs.pivotal.io site?

**Comment by lucaspinto** [comment]
One of my colleague also had an issue with his browser and told me that using youtube's *https* link should fix the problem. I have made subsequent pull requests.

**Pull request merged**
